config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create', as: :login_post
  delete '/logout', to: 'sessions#destroy', as: :logout

  namespace :pages, path: '' do
    resources :articles, path: 'yazilarim', only: %w[index show]
    resources :projects, path: 'projelerim', only: %w[index show]
    resources :tags, path: 'etiketler', only: %w[show]
    resources :categories, path: 'kategoriler', only: %w[show]
    get '/hakkimda', to: 'aboutme#index', as: :aboutme
    get '/iletisim', to: 'communication#index', as: :communication
  end

  namespace :panel, as: '', path_names: { new: 'yeni', edit: 'duzenle' } do
    get '/', to: 'panel#index', as: :panel
    resource :aboutme, except: %i[new create destroy], path: 'hakkimda', controller: 'aboutme'
    resource :communication, except: %i[new create destroy], path: 'iletisim', controller: 'communication'
    resources :projects, path: 'projelerim', controller: 'projects' do
      post :upload_image, on: :collection
    end
    resources :articles, path: 'yazilarim', controller: 'articles' do
      post :upload_image, on: :collection
    end
    resources :tags, path: 'etiketler', controller: 'tags'
    resources :categories, path: 'kategoriler', controller: 'categories'
    resources :admins, path: 'yoneticiler', controller: 'admins'
  end

  # resources :articles
  # resources :categories
  # resources :projects
  # resources :admins
  root 'main#index'
  # bu bir denemedir
end

app/controllers/panel/aboutme_controller.rb
module Panel
  class AboutmeController < ApplicationController
    before_action :select_aboutme, only: %i[show edit update]
    # after_action :send_message, only: %i[update]
    def show; end

    def edit
      return unless @aboutme.profile_photo.persisted?

      @filename = @aboutme.profile_photo.filename.to_s
      @file_size = @aboutme.profile_photo.byte_size
      @image_url = rails_blob_url(@aboutme.profile_photo)
    end

    def update
      if @aboutme.update(get_params)
        # Reset the cache
        KredisService.clear_data('aboutme')
        redirect_to(panel_path)
      else
        render :edit
      end
    end

    private

    def select_aboutme
      @aboutme = Aboutme.first
    end

    def get_params
      params.require(:aboutme).permit(:body, :profile_photo)
    end
  end
end

app/controllers/panel/admins_controller.rb
module Panel
	class AdminsController < ApplicationController
		before_action :select_admin,only: %w[ edit update destroy ]

		def index
			@admins = Admin.all
		end

		def new
			@admin = Admin.new
		end

		def create
			@admin = Admin.new(
				params.require(:admin).permit(
					:firstname,
					:lastname,
					:username,
					:email,
					:password,
					:password_confirmation
				)
			)

			if @admin.valid?
				if @admin.save
					flash[:notice] = "Admin başarıyla eklendi!"
					redirect_to(admins_path)
				else
					flash[:alert] = "Admin ekleme işlemi başarısız!"
					render :new,status: 422
				end
			else
				flash[:alert] = "Validasyon başarısız!"
				render :new,status: 422
			end
		end

		def edit

		end
		def update
			if @admin.update(params.require(:admin).permit(:firstname,:lastname,:username,:email,:password,:password_confirmation))
				flash[:notice] = "İdsi #{@admin.id} olan kayıt başarıyla güncellendi!"
				redirect_to(admins_path)
			else
				flash[:alert] = "Validasyon başarısız!"
				render :edit,status: 422
			end
		end

		def destroy
			if @admin.destroy
				flash[:notice] = "Admin başarıyla silindi!"
			else
				flash[:alert] = "Admin silmede hata meydana geldi!"
			end
			redirect_to(admins_path)
		end

		private
		def select_admin
			@admin = Admin.find(params[:id])
		end
	end
end

app/controllers/panel/application_controller.rb
module Panel
	class ApplicationController < ActionController::Base
		before_action :redirect_if_unsigned
		layout :set_layout

		def current_admin
			@current_admin ||= Admin.find_by_username(session[:admin_username]) if session[:admin_username] && Admin.exists?(username:session[:admin_username])
		end
		def signed_in?
			current_admin
		end
		def redirect_if_unsigned
			unless signed_in?
				redirect_to(root_path)
			end
		end

		private
		def set_layout
			controller_name == "panel" ? "application" : "panel"
		end

		helper_method :signed_in?,:current_admin,:redirect_if_unsigned
	end
end

app/controllers/panel/articles_controller.rb
module Panel
  class ArticlesController < ApplicationController
    before_action :select_article, only: %w[edit update destroy]

    def index
      @articles = Article.all.sort
    end

    def new
      @article = Article.new
      @categories = Category.pluck(:name)
      @tags = Tag.pluck(:title)
    end

    def create
      @article = Article.new(get_params(:title, :header, :content, :image))

      @article.category = Category.find_by_name(get_params(:category)[:category])

      @article.tags = params.require(:article).permit!['tags'].delete_if do |tag|
        !Tag.exists?(title: tag)
      end.map { |tag| Tag.find_by_title(tag) }

      if @article.valid?
        if @article.save
          @article.save_article_images
          flash[:notice] = 'Yazı başarıyla eklendi'
          KredisService.clear_data('top_articles')
          redirect_to(articles_path)

        else
          flash[:alert] = 'Kayıt sırasında beklenmeyen bir hata meydana geldi'
          @old_tags = params.require(:article)['tags']
          @categories = Category.pluck(:name)
          @tags = Tag.pluck(:title)
          render :new, status: 500
        end
      else
        flash[:alert] = 'Validasyon başarısız!'
        @old_tags = params.require(:article)['tags']
        @categories = Category.pluck(:name)
        @tags = Tag.pluck(:title)
        render :new, status: 422
      end
    end

    def edit
      get_image_datas
      @old_tags = @article.tags.pluck(:title)
      @categories = Category.pluck(:name)
      @tags = Tag.pluck(:title)
    end

    def update
      @tags = params.require(:article).permit!['tags'].delete_if do |tag|
        !Tag.exists?(title: tag)
      end.map { |tag| Tag.find_by_title(tag) }
      if Category.exists?(name: get_params(:category)[:category])
        @category = Category.find_by_name(get_params(:category)[:category])
      end

      if @article.update(get_params(:title, :header, :content,
                                    :image)) && @article.update(category: @category, tags: @tags)
        @article.save_article_images
        flash[:notice] = "Kayıt #{@article.id} başarıyla güncellendi"
        KredisService.clear_data('top_articles')
        redirect_to(articles_path)
      else
        flash[:alert] = 'Validasyon başarısız!'
        @old_tags = params.require(:article)['tags'] || @article.tags.pluck(:title)
        get_image_datas
        @categories = Category.pluck(:name)
        @tags = Tag.pluck(:title)
        render :edit, status: 422
      end
    end

    def destroy
      if @article.destroy
        flash[:notice] = 'Kayıt başarıyla silindi'
        KredisService.clear_data('top_articles')
      else
        flash[:alert] = 'Kayıt silmede hata meydana geldi'
      end
      redirect_to(articles_path)
    end

    def upload_image
      image = params[:image]

      if image.nil?
        render json: { success: 0, error: 'No image found in request' }
        return
      end

      # Use Active Storage to attach the image without an associated article
      uploaded_image = ArticleImage.create!(image: image)

      # Generate a URL for the uploaded image
      stored_image_url = rails_blob_url(uploaded_image.image)

      render json: { success: 1, file: { url: stored_image_url } }
    rescue StandardError => e
      render json: { success: 0, error: e.message }
    end

    private

    def get_params(*arr)
      params.require(:article).permit(arr)
    end

    def get_image_datas
      return unless @article.image.persisted?

      @filename = @article.image.filename.to_s
      @filesize = @article.image.byte_size
      @image_url = rails_blob_url(@article.image)
    end

    def select_article
      if Article.exists?(params[:id])
        @article = Article.find(params[:id])
      else
        render file: "#{Rails.root}/public/404.html", status: 404
      end
    end
  end
end

app/controllers/panel/categories_controller.rb
module Panel
	class CategoriesController < ApplicationController
		before_action :select_category,only: %w[ edit update destroy ]
		def index
			@categories = Category.all
		end
		def new
			@category = Category.new
		end
		def create
			@category = Category.new(params.require(:category).permit(:name))

			if @category.valid?
				if @category.save
					flash[:notice] = "Kategori başarıyla eklendi"
				else
					flash[:alert] = "Kategori eklemede hata meydana geldi!"
				end
				redirect_to(categories_path)
			else
				flash[:alert] = "validasyon başarısız!"
				render :new,status: 422
			end
		end

		def edit

		end
		def update
			if @category.update(params.require(:category).permit(:name))
				flash[:notice] = "Kategori başarıyla güncellendi"
				redirect_to(categories_path)
			else
				flash[:alert] = "Validasyon başarısız"
				render :edit,status: 422
			end
		end

		def destroy
			if @category.destroy
				flash[:notice] = "Kategori başarıyla silindi"
			else
				flash[:alert] = "Kategori silinemedi!"
			end
			redirect_to(categories_path)
		end

		private
		def select_category
			@category = Category.find(params[:id])
		end
	end
end

app/controllers/panel/communication_controller.rb
module Panel
  class CommunicationController < ApplicationController
    before_action :select_communication, only: %w[index edit update]
    def index
      @communication = Communication.first
    end

    def edit; end

    def show
      redirect_to(edit_communication_path)
    end

    def update
      if @communication.update(params.require(:communication).permit!)
        flash[:notice] = 'İletişim kısmı başarıyla güncellendi'
        redirect_to(panel_path)
      else
        flash[:alert] = 'Validasyon başarısız'
        render :edit, status: 422
      end
    end

    private

    def select_communication
      @communication = Communication.first
    end
  end
end

app/controllers/panel/panel_controller.rb
module Panel
	class PanelController < ApplicationController
	end
end

app/controllers/panel/projects_controller.rb
module Panel
  class ProjectsController < ApplicationController
    before_action :select_project, only: %i[show edit update destroy]
    def index
      @projects = Project.all.sort
      # FIXME: end_date ve start_date kısımlarında oluşan hatalar görünmüyor
    end

    def show; end

    def new
      @project = Project.new
      @categories = Category.pluck(:name)
      @tags = Tag.pluck(:title)
    end

    def create
      @project = Project.new(get_params(:title, :header, :content, :url, :end_date, :start_date, :image))

      if Category.exists?(name: get_params(:category)[:category])
        @project.category = Category.find_by_name(get_params(:category)[:category])
      end

      @form_tags = params.require(:project).permit!['tags'].delete_if { |tag| !Tag.exists?(title: tag) }
      @project.tags = @form_tags.map { |tag| Tag.find_by_title(tag) }

      if @project.valid?
        if @project.save
          @project.save_project_images
          flash[:notice] = 'Proje başarıyla eklendi'
          KredisService.clear_data('top_projects')
          redirect_to(projects_path)
        else
          @old_tags = params.require(:project)['tags']
          flash[:alert] = 'Teknik bir hatadan dolayı kayıt eklenemedi!'
          render :new, status: 422
        end
      else
        @old_tags = params.require(:project)['tags']
        @categories = Category.pluck(:name)
        @tags = Tag.pluck(:title)
        flash[:alert] = 'Validasyon başarısız!'
        render :new, status: 422
      end
    end

    def edit
      get_image_datas
      @old_tags = @project.tags.pluck(:title)
      @categories = Category.pluck(:name)
      @tags = Tag.pluck(:title)
    end

    def update
      @update_category = Category.find_by(name: params.require(:project).permit(:category)[:category])
      @update_tags = params.require(:project).permit!['tags'].delete_if do |tag|
        !Tag.exists?(title: tag)
      end.map { |tag| Tag.find_by(title: tag) }
      if @project.update(params.require(:project).permit(:title, :header, :url, :content, :start_date,
                                                         :end_date, :image)) && @project.update(category: @update_category,
                                                                                                tags: @update_tags)
        @project.save_project_images
        flash[:notice] = "Proje #{@project.id} başarıyla güncellendi"
        KredisService.clear_data('top_projects')
        redirect_to(projects_path)
      else
        @categories = Category.pluck(:name)
        @tags = Tag.pluck(:title)
        @old_tags = params.require(:project)['tags'] || @project.tags.pluck(:title)
        flash[:alert] = 'validasyon başarısız'
        get_image_datas
        render :edit, status: 422
      end
    end

    def destroy
      if @project.destroy
        flash[:notice] = 'Kayıt başarıyla silindi'
        KredisService.clear_data('top_projects')
      else
        flash[:alert] = 'Kayıt silmede hata meydana geldi'
      end
      redirect_to(projects_path)
    end

    def upload_image
      image = params[:image]

      if image.nil?
        render json: { success: 0, error: 'No image found in request' }
        return
      end

      # Use Active Storage to attach the image without an associated article
      uploaded_image = ProjectImage.create!(image: image)

      # Generate a URL for the uploaded image
      stored_image_url = rails_blob_url(uploaded_image.image)

      render json: { success: 1, file: { url: stored_image_url } }
    rescue StandardError => e
      render json: { success: 0, error: e.message }
    end

    private

    def get_params(*arr)
      params.require(:project).permit(arr)
    end

    def get_image_datas
      return unless @project.image.persisted?

      @filename = @project.image.filename.to_s
      @file_size = @project.image.byte_size
      @image_url = rails_blob_url(@project.image)
    end

    def select_project
      if Project.exists?(id: params.permit(:id)[:id])
        @project = Project.find(params.permit![:id])
      else
        render file: "#{Rails.root}/public/404.html", status: 404
      end
    end
  end
end

app/controllers/panel/tags_controller.rb
module Panel
  class TagsController < ApplicationController
    before_action :select_tag, only: %w[show edit update destroy]

    def index
      @tags = Tag.all
    end

    def show; end

    def new
      @tag = Tag.new
    end

    def create
      @tag = Tag.new(params.require(:tag).permit(:title))

      if @tag.valid?
        if @tag.save
          flash[:notice] = 'Etiket başarıyla eklendi!'
          redirect_to(tags_path)
        else
          flash[:alert] = 'Etiket eklemede bilinmeyen bir hata meydana geldi!'
          render :new, status: 422
        end
      else
        flash[:alert] = 'Validasyon başarısız!'
        render :new, status: 422
      end
    end

    def edit; end

    def update
      if @tag.update(params.require(:tag).permit(:title))
        flash[:notice] = "Etiket #{@tag.id} başarıyla güncellendi"
        redirect_to(tags_path)
      else
        flash[:alert] = 'Etiket güncellemede hata meydana geldi'
        render :edit, status: 422
      end
    end

    def destroy
      if @tag.destroy
        flash[:notice] = 'Etiket başarıyla silidi'
      else
        flash[:alert] = 'Etiket silinemedi'
      end
      redirect_to(tags_path)
    end

    private

    def select_tag
      @tag = Tag.find(params[:id])
    end
  end
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/views/panel/panel/index.html.erb
<%= stylesheet_link_tag "panel", "data-turbo-track": "reload" %>
<script src="https://kit.fontawesome.com/ae360af17e.js" crossorigin="anonymous"></script>

<div class="wrapper" data-controller="panel">
    <!-- Sidebar -->
    <aside id="sidebar" class="collapsed" data-panel-target="sidebar">
        <div class="h-100 bg-primary position-fixed" style="width:264px;">
            <div class="sidebar-logo text-center py-3">
              <%= link_to("Admin panel",panel_path)%>
            </div>
            <!-- Sidebar Navigation -->
            <ul class="sidebar-nav pt-2">
                <li class="sidebar-header">
                    Düzenlemeler
                </li>
                <li class="sidebar-item">
                    <%= link_to(edit_aboutme_path,class:"sidebar-link") do%>
                        <i class="fa-solid fa-list pe-2"></i>
                        Hakkımda düzenle
                    <%end%>
                </li>
                <li class="sidebar-item">
                    <%= link_to(edit_communication_path,class:"sidebar-link") do%>
                        <i class="fa-solid fa-list pe-2"></i>
                        İletişim düzenle
                    <%end%>
                </li>
                <li class="sidebar-item">
                    <%= link_to(projects_path,class:"sidebar-link") do%>
                        <i class="fa-solid fa-list pe-2"></i>
                        Projelerim
                    <%end%>
                </li>
                <li class="sidebar-item">
                    <%= link_to(articles_path,class:"sidebar-link") do%>
                        <i class="fa-solid fa-list pe-2"></i>
                        Yazılarım
                    <%end%>
                </li>
                <li class="sidebar-item">
                    <%= link_to(categories_path,class:"sidebar-link") do%>
                        <i class="fa-solid fa-list pe-2"></i>
                        Kategoriler
                    <%end%>
                </li>
                <li class="sidebar-item">
                    <%= link_to(tags_path,class:"sidebar-link") do%>
                        <i class="fa-solid fa-list pe-2"></i>
                        Etiketler
                    <%end%>
                </li>
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link collapsed" data-bs-toggle="collapse" data-bs-target="#auth"
                        aria-expanded="false" aria-controls="auth">
                        <i class="fa-regular fa-user pe-2"></i>
                        Admin İşlemleri
                    </a>
                    <ul id="auth" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        <li class="sidebar-item">
                            <%= link_to("Admin Kaydet",new_admin_path,class:"sidebar-link")%>
                        </li>
                        <li class="sidebar-item">
                            <%= link_to("Adminleri Görüntüle",admins_path,class:"sidebar-link")%>
                        </li>
                    </ul>
                </li>

                <li class="sidebar-item pt-2">
                  <%= link_to("Çıkış yap",logout_path,class:"sidebar-link btn btn-danger",:method => :delete,data:{turbo_method: :delete})%>
                </li>

                <!-- ####################################################### -->

                <li class="sidebar-header" hidden>
                    Multi Level Nav
                </li>
                <li class="sidebar-item" hidden>
                    <a href="#" class="sidebar-link collapsed" data-bs-toggle="collapse" data-bs-target="#multi"
                            aria-expanded="false" aria-controls="multi">
                            <i class="fa-solid fa-share-nodes pe-2"></i>
                            Multi Level
                    </a>
                    <ul id="multi" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        <li class="sidebar-item">
                            <a href="#" class="sidebar-link collapsed" data-bs-toggle="collapse"
                                    data-bs-target="#multi-two" aria-expanded="false" aria-controls="multi-two">
                                    Two Links
                            </a>
                            <ul id="multi-two" class="sidebar-dropdown list-unstyled collapse">
                                <li class="sidebar-item">
                                    <a href="#" class="sidebar-link">Link 1</a>
                                </li>
                                <li class="sidebar-item">
                                    <a href="#" class="sidebar-link">Link 2</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </aside>
    <!-- Main Component -->
    <div class="main">
      <nav class="navbar navbar-expand px-3 py-3 border-bottom sticky-top w-100 bg-success position-fixed">
            <!-- Button for sidebar toggle -->
            <button class="btn bg-light-subtle" type="button" data-bs-theme="dark" data-action="click->panel#changeVisibility">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
        <main class="content px-3 py-4 mt-5 border-top border-primary">
            <%= @flash%>
            <% unless flash.empty?%>
                <% type = case flash.first.first
                when "notice" then "success"
                when "alert" then "danger"
                when "info" then "info"
                when "warning" then "warning"
                end
                %>
                <div class="alert mt-3 alert-<%= type%> text-center"><%= flash.first.last.capitalize%></div>
            <%end%>
            <%= yield %>
        </main>
    </div>
</div>