config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create', as: :login_post
  delete '/logout', to: 'sessions#destroy', as: :logout

  namespace :pages, path: '' do
    resources :articles, path: 'yazilarim', only: %w[index show]
    resources :projects, path: 'projelerim', only: %w[index show]
    resources :tags, path: 'etiketler', only: %w[show]
    resources :categories, path: 'kategoriler', only: %w[show]
    get '/hakkimda', to: 'aboutme#index', as: :aboutme
    get '/iletisim', to: 'communication#index', as: :communication
  end

  namespace :panel, as: '', path_names: { new: 'yeni', edit: 'duzenle' } do
    get '/', to: 'panel#index', as: :panel
    resource :aboutme, except: %i[new create destroy], path: 'hakkimda', controller: 'aboutme'
    resource :communication, except: %i[new create destroy], path: 'iletisim', controller: 'communication'
    resources :projects, path: 'projelerim', controller: 'projects' do
      post :upload_image, on: :collection
    end
    resources :articles, path: 'yazilarim', controller: 'articles' do
      post :upload_image, on: :collection
    end
    resources :tags, path: 'etiketler', controller: 'tags'
    resources :categories, path: 'kategoriler', controller: 'categories'
    resources :admins, path: 'yoneticiler', controller: 'admins'
  end

  # resources :articles
  # resources :categories
  # resources :projects
  # resources :admins
  root 'main#index'
  # bu bir denemedir
end

app/views/shared/_carousel.html.erb
<%# data=array%>
<div id="carouselExampleIndicators" class="carousel slide">
  <div class="carousel-indicators">
    <% data.count.times do |c|%>
      <% if c == 0%>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <% else %>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= c%>" aria-label="Slide <%= c+1%>"></button>
      <% end%>
    <%end%>
  </div>
  <div class="carousel-inner">
    <% data.each do |i| %>
      <div class="carousel-item <%= 'active' if data.first == i%>">
        <%= image_tag(i,class:"d-block w-100")%>
      </div>
    <%end%>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_dropzone.html.erb
<%# @source,@max_files,@multiple,@filename,image_url, file_size%>
<% filename ||= nil%>
<% image_url ||= nil%>
<% file_size ||= nil%>
<div class="dropzone dropzone-default bg-warning-subtle dz-clickable form-control w-75 h-25 text-center overflow-scroll" style= "max-height:10px;" data-controller="dropzone" data-dropzone-max-file-size="5" data-dropzone-accepted-files="image/*" data-dropzone-max-files="<%= max_files || 1%>" data-upload-multiple="<%= multiple || false%>" 
  data-dropzone-filename-value="<%= filename %>" data-dropzone-imageurl-value="<%= image_url%>" data-dropzone-filesize-value="<%= file_size%>">
   <%= form.file_field source, direct_upload: true, multiple: multiple,data: { dropzone_target: 'input' } %>
   <div class="dropzone-msg dz-message needsclick">
     <h3 class="dropzone-msg-title"><%= defined?(title) ? title : "Dosyaları buraya yükleyin"%></h3>
     <span class="dropzone-msg-desc"><%= defined?(desc) ? desc : "İzin verilen maksimum dosya sayısı #{max_files || 1}'dir" %></span>
   </div>
</div>
<% content_for :css_tags do %>
  <%= stylesheet_link_tag "dropzone", "data-turbo-track": "reload" %>
<%end%>

app/views/shared/_editor.html.erb
<%# form: form %>
<%= form.hidden_field :content, data: { editor_target: "hidden_input" },required: true%>

<div
  id="editor_content"
  class="border border-2 rounded border-dark bg-white"
  data-editor-target="area"
>
</div>

app/views/shared/_footer.html.erb
<%= stylesheet_link_tag "_footer", "data-turbo-track": "reload" %>
<div class="container-fluid mt-5">
    <div class="card bg-white mx-5">
        <div class="row mb-4">
            <div class="col-md-4 col-sm-4 col-xs-4">
                <div class="footer-text pull-left">
                    <div class="d-flex">
                        <h1 class="font-weight-bold mr-2 px-3 pl-5" style="color:white; background-color:#957bda"> Tuncay Dinler </h1>
                        <h1 style="color: #f57bda;padding-left:20px"> Junior Backend Developer</h1>
                    </div>
                    <div class="social mt-2 mb-3 pt-5">
                    	<a href="https://www.instagram.com/tuncay_dinler_" style="padding-right:10px;"><%= image_tag("icons/instagram.svg",style:"width:25px;height:25px")%></a>
                    	<a href="https://www.linkedin.com/in/tuncay-dinler-a314b9260/" style="padding-right: 10px;"><%= image_tag("icons/linkedin.svg",style:"width:25px;height:25px")%></a>
                    	<a href="https://github.com/WormerKing"><%= image_tag("icons/github.svg",style:"width:25px;height:25px")%></a>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2"></div>
            <div class="col-md-2 col-sm-2 col-xs-2">
                <h5 class="heading">Services</h5>
                <ul>
                    <li>IT Consulting</li>
                    <li>Development</li>
                    <li>Cloud</li>
                    <li>Support</li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2">
                <h5 class="heading">Industries</h5>
                <ul class="card-text">
                    <li>Finance</li>
                    <li>Public Sector</li>
                    <li>Smart Office</li>
                    <li>Retail</li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2">
                <h5 class="heading">Company</h5>
                <ul class="card-text">
                    <li>About Us</li>
                    <li>Blog</li>
                    <li>Contact</li>
                    <li>Join Us</li>
                </ul>
            </div>
        </div>
        <div class="divider pb-5"> </div>
        <div class="row" style="font-size:15px;">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="pull-left text-center">
                    <p><%= image_tag("icons/c-circle-fill.svg")%> 2024 Tuncay Dinler</p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<%# stylesheet_link_tag "_navbar", "data-turbo-track": "reload" %>
<!--nav class="navbar navbar-expand-lg fixed-top navbar-scroll shadow-0" style="background-color: #ffede7;">
  <div class="container">
	<%# link_to("Anasayfa",root_path,class:"navbar-brand")%>
	<button class="navbar-toggler ps-0" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01"
	  aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="d-flex justify-content-start align-items-center">
		<i class="fas fa-bars"></i>
	  </span>
	</button>
	<div class="collapse navbar-collapse" id="navbarExample01">
	  <ul class="navbar-nav me-auto mb-2 mb-lg-0 pl-5">
		<li class="nav-item active">
		  <%# link_to("Hakkımda",pages_hakkimda_path,class:"nav-link px-3")%>
		</li>
		<li class="nav-item">
		  <%# link_to("Projelerim",pages_projects_path,class:"nav-link px-3")%>
		</li>
		<li class="nav-item">
		  <%# link_to("Yazılarım",pages_articles_path,class:"nav-link px-3")%>
		</li>
	  </ul>

	  <ul class="navbar-nav flex-row">
		<li class="nav-item">
		  <%# if signed_in? %>
			<%# link_to("Panel",panel_path,class:"nav-link px-3")%>
		  <%# else %>
			<%# link_to("Giriş Yap",login_path,class:"nav-link px-3")%>
		  <%# end %>
		</li>
	  </ul>
	</div>
  </div>
</nav-->
<nav class="navbar navbar-expand-lg fixed-top bg-info-subtle">
	  <div class="container py-1">
      <% if ["articles","projects","categories","tags"].include?(controller_name)%> 
        <button id="sidebarToggle" class="btn btn-outline-primary me-5" data-action="click->pages-sidebar#toggleSidebar">
          <span class="navbar-toggler-icon">
        </button>
	  	<%end%>
			<%= link_to("Anasayfa",root_path,class:"navbar-brand fs-4")%>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
			  <div class="navbar-nav ms-auto fs-6">
				<%= link_to("Hakkımda",pages_aboutme_path,class:"nav-link text-dark px-3","aria-current"=>"page")%>
				<%= link_to("Projelerim",pages_projects_path,class:"nav-link text-dark px-3")%>
				<%= link_to("Yazılarım",pages_articles_path,class:"nav-link text-dark px-3")%>
				<%= link_to("İletişim",pages_communication_path,class:"nav-link text-dark px-3")%>
				<% if signed_in?%>
					<%= link_to("Panel",panel_path,class:"nav-link text-dark px-3")%>
				<% end %>
			  </div>
			</div>
	  </div>
</nav>

app/views/shared/_sidebar.html.erb
<%= stylesheet_link_tag "_sidebar", "data-turbo-track": "reload" %>
<div class="sidebar text-center mt-5 pt-5 active" id="sidebar" data-pages-sidebar-target="sidebar">
    <h3 class="p-3">Kategoriler</h3>
    <div class="categories">
        <ul class="list-group">
          <% get_categories.each do |key,val|%>
              <li class="list-group-item">
                  <%= link_to(
                    pages_category_path(string_to_url(key)),
                    class:"d-flex justify-content-between text-decoration-none text-dark") do %>
                    <%= key %> <strong><%= val%></strong>
                  <% end %>
              </li>
            <%end%>
    </div>
    <hr>
    <h3 class="p-3">Etiketler</h3>
    <div class="tags">
        <ul class="list-group">
          <% get_tags.each do |key,val|%>
              <li class="list-group-item">
                <%= link_to(
                  pages_tag_path(string_to_url(key)),
                  class:"d-flex justify-content-between text-decoration-none text-dark") do
                %>  
                    <%= key %> <strong><%= val%></strong>
                  <% end %>
              </li>
            <%end%>
        </ul>
    </div> 
</div>

<% content_for :body_attr do %>
    data-controller="pages-sidebar"
<% end %>